ci:
  autofix_prs: true
  autofix_commit_msg: 'chore: auto fixes from pre-commit.com hooks'
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.patch$'
      - id: end-of-file-fixer
        exclude: '\.patch$'
      - id: check-added-large-files
        args: ['--maxkb=100']
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
