name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [ 7, 8, 9, 10, 11, 12, 12.0.1, 13, 14, 15, 16, 17 ]
        # tool: [ clang-format, clang-tidy, clang-query ]
        # os_name: [ linux, windows, macosx ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Download and check version ${{ matrix.version }} on Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          gh release download --pattern 'clang-format-${{ matrix.version }}_windows-amd64.exe'
          ./clang-format-${{ matrix.version }}_windows-amd64.exe --version

          gh release download --pattern 'clang-tidy-${{ matrix.version }}_windows-amd64.exe'
          ./clang-tidy-${{ matrix.version }}_windows-amd64.exe --version

          gh release download --pattern 'clang-query-${{ matrix.version }}_windows-amd64.exe'
          ./clang-query-${{ matrix.version }}_windows-amd64.exe --version

      - name: Download and check version ${{ matrix.version }} on Unix
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            pattern='linux-amd64'
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            pattern='macosx-amd64'
          fi

          gh release download --pattern "clang-format-${{ matrix.version }}_${pattern}"
          gh release download --pattern "clang-tidy-${{ matrix.version }}_${pattern}"
          gh release download --pattern "clang-query-${{ matrix.version }}_${pattern}"

          chmod +x clang-*${{ matrix.version }}_${pattern}

          ./clang-query-${{ matrix.version }}_${pattern} --version
          ./clang-format-${{ matrix.version }}_${pattern} --version
          ./clang-tidy-${{ matrix.version }}_${pattern} --version
