name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        version: [ 7, 8, 9, 10, 11, 12, 12.0.1, 13, 14, 15, 16, 17 ]
        # tool: [ clang-format, clang-tidy, clang-query ]
        # os_name: [ linux, windows, macosx ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Download and check version ${{ matrix.version }} on Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          gh release download --pattern 'clang-format-${{ matrix.version }}_windows-amd64.exe'
          ./clang-format-${{ matrix.version }}_windows-amd64.exe --version

          gh release download --pattern 'clang-tidy-${{ matrix.version }}_windows-amd64.exe'
          ./clang-tidy-${{ matrix.version }}_windows-amd64.exe --version

          gh release download --pattern 'clang-query-${{ matrix.version }}_windows-amd64.exe'
          ./clang-query-${{ matrix.version }}_windows-amd64.exe --version

      - name: Download and check version ${{ matrix.version }} on Linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          gh release download --pattern 'clang-format-${{ matrix.version }}_linux-amd64'
          ./clang-format-${{ matrix.version }}_linux-amd64 --version

          gh release download --pattern 'clang-tidy-${{ matrix.version }}_linux-amd64'
          ./clang-tidy-${{ matrix.version }}_linux-amd64 --version

          gh release download --pattern 'clang-query-${{ matrix.version }}_linux-amd64'
          ./clang-query-${{ matrix.version }}_linux-amd64 --version

      - name: Download and check version ${{ matrix.version }} on MacOS
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          gh release download --pattern 'clang-format-${{ matrix.version }}_macosx-amd64'
          ./clang-format-${{ matrix.version }}_macosx-amd64 --version

          gh release download --pattern 'clang-tidy-${{ matrix.version }}_macosx-amd64'
          ./clang-tidy-${{ matrix.version }}_macosx-amd64 --version

          gh release download --pattern 'clang-query-${{ matrix.version }}_macosx-amd64'
          ./clang-query-${{ matrix.version }}_macosx-amd64 --version
